name: dart_app
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  custom_lint: ^0.6.4
  lint_plugin: 
    path: ../lint_plugin
dependencies:
  fast_immutable_collections: ^10.2.4
